"""AgentTool — wraps an Agent as a :class:`BaseTool`.

When an LLM sees an AgentTool, it treats it like any other tool — it
doesn't know there's an agent behind it.  The agent runs independently
and its result is returned as plain text to the calling agent's tool loop.

Design
------
:class:`BaseTool` follows the "one class = one tool" pattern: ``name`` and
``description`` are set via ``__init_subclass__`` class-keyword arguments,
and ``schema_dict`` is auto-generated from the ``__call__`` signature.

Since each AgentTool wraps a *different* agent with a *different* name, we
use a **factory function** (:func:`agent_tool`) that dynamically creates a
``BaseTool`` subclass per call via ``type()``.  This respects BaseTool's
design — the resulting class has proper ``__function_name__`` /
``__function_description__`` class variables and a fully annotated
``__call__``, so ``schema_dict`` is generated automatically by Pydantic.

Usage::

    tool = agent_tool(
        my_agent,
        name="translate_to_chinese",
        description="Translate text to Chinese",
        llm=chat_model,
    )
    # tool is a BaseTool subclass instance — schema_dict auto-generated
    result = await tool(task="Hello, how are you?")
"""

from __future__ import annotations

import typing as t

from bookscout.tools import BaseTool
from bookscout.tools import Property

from .agent import Agent
from .context import AgentContext
from .context import AgentRunState

if t.TYPE_CHECKING:
    from bookscout.llm import ChatModel


def agent_tool(
    agent: Agent,
    *,
    name: str,
    description: str,
    llm: ChatModel | None = None,
) -> BaseTool:
    """Create a :class:`BaseTool` that delegates execution to *agent*.

    This is a **factory function**, not a class.  It dynamically creates a
    ``BaseTool`` subclass with the given ``name`` and ``description``,
    defining ``__call__`` with proper type annotations so that
    ``schema_dict`` is auto-generated by BaseTool's Pydantic-powered
    schema builder.

    The wrapped agent runs in isolation — it gets a fresh
    :class:`AgentContext` with no conversation inheritance from the caller.

    Args:
        agent: The agent to wrap.
        name: The function name the LLM will call.
        description: The tool description for the LLM.
        llm: Optional ChatModel for delegated execution.

    Returns:
        A ``BaseTool`` instance whose ``__call__`` runs the agent.
    """

    async def __call__(self: BaseTool, *, task: str) -> str:  # noqa: N807
        """Execute the wrapped agent with the given task.

        Creates a fresh :class:`AgentContext` (no conversation inheritance)
        and runs the agent.  Returns the agent's text output as a plain
        string.

        Args:
            task: The task description for the delegated agent.

        Returns:
            The agent's text output.
        """
        agent_: Agent = self._agent  # type: ignore[attr-defined]
        llm_: ChatModel | None = self._llm  # type: ignore[attr-defined]

        if llm_ is None:
            return f"Error: AgentTool '{self.__function_name__}' has no ChatModel configured"

        ctx = AgentContext(
            llm=llm_,
            prompt_params={"task": task},
            agent_state=AgentRunState.IDLE,
        )
        from bookscout.llm.types import UserMessage as _Usr

        result = await agent_.run([_Usr(content=task)], ctx=ctx)
        return result.text or ""

    # Build Annotated[type, Property(...)] for the `task` parameter so
    # that BaseTool's schema generator picks up the description.
    task_annotated = t.Annotated[str, Property(description="The task to delegate to the agent.")]
    __call__.__annotations__["task"] = task_annotated

    # Dynamically create the BaseTool subclass.
    # __init_subclass__(name=, description=) sets __function_name__ and
    # __function_description__ as ClassVars, and schema_dict is auto-
    # generated from __call__'s signature by _build_schema_dict().
    cls_name = f"_{agent.name.title().replace('_', '')}Tool"
    cls = type(
        cls_name,
        (BaseTool,),
        {
            "__call__": __call__,
            "__doc__": description,
        },
        name=name,
        description=description,
    )

    # Instantiate and attach the captured agent/llm.
    instance = cls()
    instance._agent = agent  # type: ignore[attr-defined]
    instance._llm = llm  # type: ignore[attr-defined]

    return instance


# Keep AgentTool as an alias for the factory, so existing imports work.
# Users can call either ``AgentTool(...)`` or ``agent_tool(...)``.
AgentTool = agent_tool
