# Copyright 2026 BoChen SHEN
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from __future__ import annotations

import inspect
import json
import re
import typing as t

from pydantic import BaseModel
from pydantic import create_model
from pydantic.fields import FieldInfo
from pydantic.fields import _FromFieldInfoInputs


class Function(t.NamedTuple):
    """LLM tool-call function specification."""

    name: str
    arguments: str
    """JSON-serialised argument string."""


class ToolCallsParams(t.NamedTuple):
    """Pending tool call emitted by the LLM (before execution)."""

    call_id: str
    function: Function


class ToolCalls(t.NamedTuple):
    """Resolved tool call result (after execution)."""

    call_id: str
    content: str | list[str]


class FunctionDict(t.TypedDict):
    """OpenAI-compatible function definition."""

    name: str
    """Tool function name."""

    description: str
    """Tool function description."""

    parameters: dict[str, t.Any] | None
    """JSON Schema for tool parameters."""


class SchemaDict(t.TypedDict):
    """OpenAI-compatible schema dict."""

    type: t.Literal["function"]
    """Schema type. Fixed to "function"."""

    function: FunctionDict
    """Tool function definition."""


# pylint: disable-next=subclassed-final-class
class Property(FieldInfo):  # type: ignore
    """Tool parameter annotation, built on Pydantic :class:`FieldInfo`.

    Supports all Pydantic ``Field`` parameters 鈥?``description``, ``examples``,
    ``default``, ``gt``, ``ge``, ``lt``, ``le``, ``min_length``, ``max_length``,
    ``pattern``, and more.

    Usage::

        from typing import Annotated


        class GetWeather(
            BaseTool,
            name="get_weather",
            description="Get weather for a location",
        ):
            async def __call__(
                self,
                location: Annotated[
                    str,
                    Property(description="City name", min_length=1, max_length=100),
                ],
                unit: Annotated[
                    t.Literal["celsius", "fahrenheit"],
                    Property(description="Temperature unit", default="celsius"),
                ] = "celsius",
            ) -> str: ...
    """

    def __init__(self, default: t.Any = ..., **kwargs: t.Unpack[_FromFieldInfoInputs]) -> None:
        # Map our preferred names to Pydantic's internal names
        if "example" in kwargs and "examples" not in kwargs:
            kwargs["examples"] = [kwargs.pop("example")]  # type: ignore[typeddict-item]
        super().__init__(default=default, **kwargs)


_PASCAL_RE = re.compile(r"([A-Z]+)([A-Z][a-z])")
_CAMEL_RE = re.compile(r"([a-z\d])([A-Z])")


def _pascal_to_snake(name: str) -> str:
    """``GetWeather`` 鈫?``get_weather``"""
    s = _PASCAL_RE.sub(r"\1_\2", name)
    s = _CAMEL_RE.sub(r"\1_\2", s)
    return s.lower()


class BaseTool:
    """Abstract base for all callable tools.

    Subclasses define their parameters via type-annotated ``__call__``
    signatures.  ``Property`` annotations add rich metadata.  The JSON
    Schema is automatically generated by Pydantic.

    ::

        class WeatherTool(
            BaseTool,
            name="get_weather",
            description="Get current weather",
        ):
            async def __call__(
                self,
                location: Annotated[
                    str,
                    Property(description="City", min_length=1),
                ],
            ) -> str:
                return f"Sunny in {location}"

    Tools are passed to :class:`ToolExecutor` for dispatching.
    """

    __function_name__: t.ClassVar[str]
    __function_description__: t.ClassVar[str]

    def __init_subclass__(
        cls,
        name: str | None = None,
        description: str | None = None,
        **kwargs: t.Any,
    ) -> None:
        super().__init_subclass__(**kwargs)
        cls.__function_name__ = name or _pascal_to_snake(cls.__name__)
        cls.__function_description__ = description or (cls.__doc__ or "").strip()

    def __call__(self, **kwargs: t.Any) -> t.Any:
        raise NotImplementedError

    @property
    def schema_dict(self) -> SchemaDict:
        """JSON Schema dict ready for OpenAI / LLM function-calling API."""
        return _build_schema_dict(self)


def _build_schema_dict(tool: BaseTool) -> SchemaDict:
    """Generate the OpenAI-compatible schema dict from the tool's signature."""
    params_model = _make_params_model(type(tool))
    params_schema = params_model.model_json_schema()

    # Clean up Pydantic artefacts for a lean OpenAI-compatible schema
    params_schema.pop("title", None)
    params_schema.pop("description", None)
    params_schema.setdefault("type", "object")
    for prop in params_schema.get("properties", {}).values():
        if isinstance(prop, dict):
            prop.pop("title", None)
            # Pydantic renders Optional[T] as anyOf: [{type: T}, {type: null}]
            # 鈫?keep as-is, LLM APIs accept it.

    return SchemaDict(
        type="function",
        function=FunctionDict(
            name=tool.__function_name__,
            description=tool.__function_description__,
            parameters=params_schema if params_schema.get("properties") else None,
        ),
    )


def _make_params_model(tool_cls: type[BaseTool]) -> type[BaseModel]:
    """Dynamically create a Pydantic model from ``__call__`` parameters."""
    sig = inspect.signature(tool_cls.__call__)
    hints = t.get_type_hints(tool_cls.__call__, include_extras=True)

    fields: dict[str, tuple[type, FieldInfo]] = {}

    for param_name, param in sig.parameters.items():
        if param_name == "self":
            continue

        annotation = hints.get(param_name, str)
        field_info = _extract_field_info(annotation)

        # Apply default if present
        if param.default is not inspect.Parameter.empty:
            field_info = _merge_default(field_info, param.default)

        base_type = _unwrap_annotated(annotation)
        fields[param_name] = (base_type, field_info)

    if not fields:
        # Empty params 鈫?simple object model
        return create_model("Params", __base__=BaseModel)

    return create_model("Params", __base__=BaseModel, **fields)  # type: ignore[call-overload, no-any-return]


def _extract_field_info(annotation: t.Any) -> FieldInfo:
    """Extract :class:`FieldInfo` from an ``Annotated`` type, or build a new one."""
    if t.get_origin(annotation) is t.Annotated:
        for meta in t.get_args(annotation)[1:]:
            if isinstance(meta, FieldInfo):
                return meta
    return FieldInfo()


def _unwrap_annotated(annotation: t.Any) -> type[t.Any]:
    """Return the base type from ``Annotated[base, ...]``."""
    if t.get_origin(annotation) is t.Annotated:
        return t.get_args(annotation)[0]  # type: ignore[no-any-return]
    return annotation  # type: ignore[no-any-return]


def _merge_default(field_info: FieldInfo, default: t.Any) -> FieldInfo:
    """Return a new FieldInfo with *default* applied, preserving all metadata."""
    if not field_info.is_required():
        return field_info  # already has a default

    new_fi = FieldInfo(
        default=default,
        description=field_info.description,
        examples=field_info.examples,
        json_schema_extra=field_info.json_schema_extra,
    )
    # Replay constraint metadata from the original (Gt, Le, MinLen, 鈥?
    for item in field_info.metadata:
        new_fi.metadata.append(item)
    return new_fi


class ToolExecutor:
    """Dispatch :class:`ToolCallsParams` to registered :class:`BaseTool`
    instances.

    Args:
        tools: Sequence of tools to register, keyed by ``__function_name__``.
    """

    def __init__(self, tools: t.Sequence[BaseTool]) -> None:
        self._tools: dict[str, BaseTool] = {tool.__function_name__: tool for tool in tools}

    async def execute(self, params: ToolCallsParams) -> ToolCalls:
        """Execute a single tool call and return the result."""
        func_name = params.function.name
        call_id = params.call_id

        if func_name not in self._tools:
            return ToolCalls(call_id=call_id, content=f"Tool '{func_name}' not available")

        tool = self._tools[func_name]
        try:
            args: dict[str, t.Any] = json.loads(params.function.arguments)
        except json.JSONDecodeError as exc:
            return ToolCalls(call_id=call_id, content=f"Invalid args for '{func_name}': {exc}")

        try:
            result = tool(**args)
            if isinstance(result, t.Awaitable):
                result = await result
        # pylint: disable-next=broad-exception-caught
        except Exception as exc:
            return ToolCalls(call_id=call_id, content=f"Error in '{func_name}': {exc}")

        if isinstance(result, str):
            content: str | list[str] = result
        elif isinstance(result, list):
            content = [json.dumps(r) if not isinstance(r, str) else r for r in result]
        else:
            content = json.dumps(result)
        return ToolCalls(call_id=call_id, content=content)

    async def execute_many(self, calls: t.Sequence[ToolCallsParams]) -> list[ToolCalls]:
        """Execute multiple tool calls sequentially."""
        return [await self.execute(c) for c in calls]
